backend:
  name: git-gateway
  branch: main # YAN 'master' li gor navê branch'ê te li GitHub

media_folder: "assets/images" # Cihê helgirtina wêneya
public_folder: "/assets/images"

collections:
  - name: "teachers"
    label: "مامۆستایان"
    folder: "_data/teachers" # Ev tenê bo organîzekirinê ye, em ê faylekê bikar bînin
    create: true
    slug: "{{id}}"
    fields:
      - {label: "ID (ب ئینگلیزی، بێ سپەیس، نابیت بهێتە گوهۆرین)", name: "id", widget: "string"}
      - {label: "ناڤێ تەمام", name: "name", widget: "string"}
      - {label: "وێنێ پرۆفایلی", name: "profileImage", widget: "image"}
      - {label: "کورتەیەک لسەر", name: "bio", widget: "text"}
      - {label: "ژمارا تەلەفونێ", name: "phone", widget: "string"}
      - label: "تۆرێن جڤاکی"
        name: "social"
        widget: "object"
        fields:
          - {label: "یوتیوب", name: "youtube", widget: "string", required: false}
          - {label: "تێلەگرام", name: "telegram", widget: "string", required: false}
          - {label: "فەیسبوک", name: "facebook", widget: "string", required: false}
      - label: "جهێن وانەگۆتنێ"
        name: "locations"
        widget: "list"
        fields:
          - {label: "ناڤێ جهی", name: "name", widget: "string"}
          - {label: "Coordinates (lat, long)", name: "coordinates", widget: "list"}
          - {label: "دەوام", name: "schedule", widget: "string"}
          - {label: "وانا لێ دهێتە گۆتن", name: "lessonTaught", widget: "string"}

  - name: "pirtukxane"
    label: "پەرتوکخانە"
    folder: "_data/pirtukxane"
    create: true
    fields:
      - {label: "ناڤێ پەرتوکێ", name: "title", widget: "string"}
      - {label: "نڤیسەر", name: "author", widget: "string"}
      - {label: "بابەت", name: "category", widget: "string"}
      - {label: "وێنێ بەرگی", name: "coverImage", widget: "image"}
      - {label: "کورتە", name: "description", widget: "text"}
      - {label: "لینکێ خواندنێ", name: "readUrl", widget: "string"}
      - {label: "لینکێ داگرتنێ", name: "downloadUrl", widget: "string"}
  
  # Hêj bêtir dikarin bên zêdekirin...
